### PR TITLE
Reapply #211 and fix multiarch-manifest for armhf

### PR DESCRIPTION
**Pull request by aalaesar**
This PR revert the revert of #211 and fix the missing arch name conversion for the multi-arch manifest

### CODE REVIEW

**Review by fasaxc — APPROVED** [review]

**Comment by caseydavenport** [comment]
@aalaesar so it looks like somewhere between this PR and the recent calioctl PR broke our continuous delivery targets for pushing images.

I'm seeing the following when I try:

```
docker run -t --entrypoint /bin/sh -v /home/casey/.docker/config.json:/root/.docker/config.json calico/go-build:v0.52 -c "/usr/bin/manifest-tool push from-args --platforms linux/arm/v7,linux/amd64,linux/s390x,linux/arm64,linux/ppc64le --template calico/ctl:master-ARCH --target calico/ctl:master"
FATA[0001] Inspect of image "calico/ctl:master-arm" failed with error: manifest unknown: manifest unknown 
make: *** [Makefile.common:726: sub-manifest-calico___ctl] Error 1
```

Do you have time to look at this soon? Otherwise we may need to revert the changes.

**Comment by aalaesar** [comment]
> @aalaesar so it looks like somewhere between this PR and the recent calioctl PR broke our continuous delivery targets for pushing images.
> 
> I'm seeing the following when I try:
> 
> ```
> docker run -t --entrypoint /bin/sh -v /home/casey/.docker/config.json:/root/.docker/config.json calico/go-build:v0.52 -c "/usr/bin/manifest-tool push from-args --platforms linux/arm/v7,linux/amd64,linux/s390x,linux/arm64,linux/ppc64le --template calico/ctl:master-ARCH --target calico/ctl:master"
> FATA[0001] Inspect of image "calico/ctl:master-arm" failed with error: manifest unknown: manifest unknown 
> make: *** [Makefile.common:726: sub-manifest-calico___ctl] Error 1
> ```
> 
> Do you have time to look at this soon? Otherwise we may need to revert the changes.

Hi,
issue is with the missing arch variant
it should be 
`docker run -t --entrypoint /bin/sh [....] --template calico/ctl:master-ARCHVARIANT --target calico/ctl:master`

like [here](https://github.com/projectcalico/go-build/blob/master/Makefile#L104)
I'll check If I overlooked this target for calicoctl 😞

**Comment by aalaesar** [comment]
@caseydavenport 
correction. I overlooked it in the Makefile.common, [here ](https://github.com/projectcalico/go-build/blob/master/Makefile.common#L726)😞

**Comment by aalaesar** [comment]
@caseydavenport 
I made a [PR](https://github.com/projectcalico/go-build/pull/242) for the patched line.
Given your logs I see the list of platforms is good. so no more changes should be needed.
Regards

**Pull request merged**
