### PR TITLE
Added Dockerfile.s390x to support for s390x

### PR DESCRIPTION
**Pull request by guirish**
Added Dockerfile.s390x file to support for s390x

### CODE REVIEW

**Comment by djlwilder** [comment]
Woo-hoo!  Another architecture to add to the mix.  @fasaxc @tomdee  @deitch :)

**Comment by deitch** [comment]
Cool! Looks like we will need to add more `qemu` etc for the `amd64` image.

First need to get it merged in, o' course!

**Comment by guirish** [comment]
@djlwilder , I will update the Dockerfile.s390x for goveralls binary, taking reference of Dockerfile.ppc64le.

**Comment by guirish** [comment]
@fasaxc it picks and updates **BUILDARCH=s390x** as required, on executing "uname -m" command.

**Pull request merged**
