### PR TITLE
update dockerfile goversion for architectures.

### LINKED ISSUE #417: why not upgrade to golang:1.19.5 for all platforms?
the pr [1.19.5 just update amd64](https://github.com/projectcalico/go-build/pull/414).
why not update all others?
like 
```
Dockerfile.s390x,
Dockerfile.ppc64le,
Dockerfile.armv7,
Dockerfile.arm64
```

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

/kind cleanup

1 add go version to other architectures .
2 change the base image alpine to 3.17.

fix #417

### CODE REVIEW

**Comment by frozenprocess** [comment]
@yanggangtony, did you try building Calico with this `go-build` change to see if there are any errors or not?

**Comment by yanggangtony** [comment]
>  did you try building Calico with this `go-build` change to see if there are any errors or not?
@frozenprocess 
Hi , thanks for review. 
Actually i known go-build is calico's outer inference , i saw that is the branch tag?
I am  also a newbie to calico community. 

How did it test local code for that?

**Comment by frozenprocess** [comment]
> > did you try building Calico with this `go-build` change to see if there are any errors or not?
> > @frozenprocess
> > Hi , thanks for review.
> > Actually i known go-build is calico's outer inference , i saw that is the branch tag?
> > like
> 
> ```
> /calico/metadata.mk  , 
> # The version of github.com/projectcalico/go-build to use.
> GO_BUILD_VER = v0.78
> ```
> 

> I am also a newbie to calico community.
Welcome! 
I would highly recommend checking the `#contributors` channel in the Calico Users [Slack group](https://slack.projectcalico.org/). It is the place to share, ask and connect with other devs and engineers to talk Calico!
> How did it test local code for that?
It is pretty easy,```
# clone https://github.com/projectcalico/calico
make image all CALICO_BUILD=myrepo/myimage:mytag
```

**Comment by yanggangtony** [comment]
@frozenprocess 
thanks for the patient.
I will test it in later and response my result here.
:ok_hand:

**Comment by yanggangtony** [comment]
1 first i build go-build in my local pc .
image

then get images about :
image

2 : build calico project 
企业微信截图_e10e2989-c5b9-44bc-b6ea-bc6cfc5f764f
企业微信截图_3a7a5940-1b5f-4491-b7ab-a4f420b92bd2

企业微信截图_3a7a5940-1b5f-4491-b7ab-a4f420b92bd2


when build arm image in my amd64 machine, docker buildx can not do it , it get error before pic.

so maybe i should found a arm64 machine to test that ? is that right? 

or is there a good way to test cross image for calico build?

**Review by frozenprocess — APPROVED** [review]
/LGTM

**Pull request merged**
