### PR TITLE
Add 32 bits armhf arch to the Image

### PR DESCRIPTION
**Pull request by aalaesar**
Add 32 bits arm architecture resources to the go-build image.

This build has been tested for cross-compiling the arm calico images locally

### CODE REVIEW

**Comment by aalaesar** [comment]
Hmm ??
CI passed OK while running nothing ... Is this ok ?
I have confirmation the Dockerfile.arm has a base image issue that **_should_** make the CI fail

**Comment by lwr20** [comment]
> CI passed OK while running nothing ... Is this ok ?
> I have confirmation the Dockerfile.arm has a base image issue that should make the CI fail

Looks like CI doesn't have a build for `arm`. You'll need to add it to this list:
https://github.com/projectcalico/go-build/blob/master/.semaphore/semaphore.yml#L60

**Comment by aalaesar** [comment]
> > CI passed OK while running nothing ... Is this ok ?
> > I have confirmation the Dockerfile.arm has a base image issue that should make the CI fail
> 
> Looks like CI doesn't have a build for `arm`. You'll need to add it to this list:
> https://github.com/projectcalico/go-build/blob/master/.semaphore/semaphore.yml#L60
Hello
I added armhf  to semaphore.yml

**Comment by aalaesar** [comment]
hello @lmm @lwr20 ,
how is the ci on semaphore 2 ?
I can't have feedback of integration issues until I try to build other components:

- Just fixed a missing GOARCH conversion for armv5-7 (found this one while testing builds locally for calicoctl)

also, I suppose  this PR must be merged & tagged **in priority** for  the other components to start building correctly on other CI because of the armhf addition.

**Comment by lwr20** [comment]
CI Passed on sem v2.

**Comment by aalaesar** [comment]
> CI Passed on sem v2.

Yes thank you @lwr20   
unfortunately the integration test with upstream projects only partially cover the changes for ARCH=armhf. (At least there is no regression with the introduction of GOARCH_FLAGS.) but the arch name conversion issue I fixed today couldn't have been detected by the CI.  
I'm afraid this is a chicken-egg problem: can't test armhf on upstream because upstream has no support for it yet ; upstream has no support for armhf because this PR is not merged yet.  

So, what can be done ?

**Comment by lwr20** [comment]
@fasaxc ^  Would appreciate your thoughts on this.

**Comment by fasaxc** [comment]
I see a lot of these warnings in the build output from docker: 
```
[Warning] The requested image's platform (linux/arm) does not match the detected host platform (linux/amd64) and no specific platform was requested
```
Has something gone awry there?

**Comment by aalaesar** [comment]
> I see a lot of these warnings in the build output from docker:
> 
> ```
> [Warning] The requested image's platform (linux/arm) does not match the detected host platform (linux/amd64) and no specific platform was requested
> ```
> 
> Has something gone awry there?

yes I noted the warnings too and checked the test for arm64, they were also here so I supposed it was not a regression, but on second thought is was a test on the same branch, maybe the warning are just for this PR ? how to check ?

**Comment by aalaesar** [comment]
> Has something gone awry there?

@fasaxc 
Just saw that I could check all the semaphore tests  
so the warning appeared on the [arm64](https://tigera.semaphoreci.com/jobs/686b8aa3-f016-45c0-88e6-9affd523f8e5) & [ppc64le](https://tigera.semaphoreci.com/jobs/cdbf171c-c13d-46ff-8d3a-23cd957d9fd1) builds last week [on this commit](https://github.com/projectcalico/go-build/commit/7e4a9398d46665ebb81700e7bbcd9bc07f3419e5) with no major changes. 
 
A quick google suggest this could be related to a docker update to 20.10+ on the semaphore platform. The engine change how it reports arch "misconfiguration?" (not clear). see this [comment](https://github.com/docker/for-linux/issues/1170#issuecomment-750371249).

Some changes may be required to get rid of this warning but this is not the scope of the PR.

**Review by fasaxc — APPROVED** [review]
Let's give this a shot

**Comment by fasaxc** [comment]
@aalaesar Please join the Calico slack `#contributors` channel so we can coordinate and discuss the remaining work...

**Pull request merged**
